### ISSUE TITLE
KeyError: 'ʻ'

### ISSUE THREAD

**Issue by keithbriggs** [nschloe/betterbib#153] opened 2020-06-18 09:55 UTC
I'm getting this error, even though the character 'ʻ' is not in my bibtex file.

me:~/bibtex> cat foo.bib | betterbib

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1851/1851 [04:04<00:00,  7.58it/s]

Total number of entries: 1851
Found: 498
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/latexcodec/codec.py", line 733, in _get_latex_chars_tokens_from_char
    return self.table.latex_map[c]
KeyError: 'ʻ'

**Comment by nschloe** [comment] 2020-06-18 10:04
I need to the offending entry to reproduce. Try bisecting.

**Comment by keithbriggs** [comment] 2020-06-18 10:08
How do I bisect when the file has 1851 entries?

Why can't betterbib catch the exception "UnicodeEncodeError: 'latex' codec can't encode character '\u02bb' in position 0: don't know how to translate 'ʻ' into latex" and print some useful debug information?

Keith

________________________________

**Comment by nschloe** [comment] 2020-06-18 10:25
> How do I bisect when the file has 1851 entries?

That's at most 11 iterations.

> Why can't betterbib catch the exception "UnicodeEncodeError: 'latex' codec can't encode character '\u02bb' in position 0: don't know how to translate 'ʻ' into latex" and print some useful debug information?

Because I don't know here in the code the error comes from.

**Comment by keithbriggs** [comment] 2020-06-18 10:41
You mean keep splitting the file into 2 new files?

But there are about 30  @strings defined at the top which would have to be copied into each half.



________________________________

**Comment by nschloe** [comment] 2020-06-18 10:46
Just comment out.

**Comment by keithbriggs** [comment] 2020-06-18 10:47
The file has 23096 lines 🙁


________________________________

**Comment by nschloe** [comment] 2020-06-18 11:03
If you cannot provide a minimal reproducible example, there is nothing I can do to fix the error.

If you'd like to proceed here, perhaps it's best to make yourself familiar with your text editor. The fact that the file has 23k lines really doesn't matter; after 4 rounds of bisection it only has 1.5k; this should be a really fast process.

**Comment by keithbriggs** [comment] 2020-06-18 11:03
I can't think of an easy way to do this.   I made this change:

        # handle things that latexcodec can't handle yet
        repl = {
            # https://github.com/mcmtroffaes/latexcodec/issues/74:
            # "\u2217": "\\ast",
            # https://github.com/mcmtroffaes/latexcodec/issues/83:
            "\ufffd": "?",
            "ʻ": "'", # KB 2020-06-18
            "ʼ": "'", # KB 2020-06-18
}

and the problem goes away.   But now I get (from LaTeX \guillemotleft)

UnicodeEncodeError: 'latex' codec can't encode character '\xab' in position 0: don't know how to translate '«' into latex

so there are definitely several characters missing and I think the code needs to handle these gracefully, not crash.

K
________________________________

**Comment by keithbriggs** [comment] 2020-06-18 11:12
I've been using vi since about 1980, but I never had to insert by line number before.

Instead I made it print out bibtex_key at line 187, and I got the fist bad entry straight away:

@incollection{Kruger:Faszination:Whaley,
  author={Whaley, Diana},
  editor={Kr\"uger, Jana and Busch, Vivian and Seidel, Katharina and Zimmermann, Christiane and Zimmermann, Ute},
  year=2017,
  pages={379--409},
  title={A far-travelled word: Old Norse \emph{skei{\dh}}\ `racecourse, running track' in early literature and place-names},
  booktitle={Die Faszination des Verborgenen und seine Entschl\"usselung: \emph{R\=a{\dh}i s\=aR kunni}},
  series={Beitr\"age zur Runologie, Skandinavistischen Medi\"avistik und Germanischen Sprachwissenschaft},
  volume=101,
  publisher={De Gruyter},
  address={Berlin},
  isbn={9783110548136},
}

________________________________

**Comment by nschloe** [comment] 2020-06-18 11:38
Perfect, I can reproduce the error. Looking at it now.

> I've been using vi since about 1980, 

(I'm also a vim guy btw. When commenting out, I just block select the column and insert `#` in a couple of thousand lines. Revert with `u`.)

**Comment by nschloe** [comment] 2020-06-18 12:04
Fixed now. Let me know if you have any more issues.

**Closed** 2020-06-18 12:03 UTC

**Comment by keithbriggs** [comment] 2020-06-18 12:36
Is this the fix:

     "\u02bb": "'",
     "\u02bc": "'",

?   I think those need to be turned into backquotes, not forward quotes.

There will also need to be a fix for « and the corresponding right guillemot.



________________________________

**Comment by nschloe** [comment] 2020-06-18 12:48
Yes. If you have a better idea, or more suggestions, here is where you can edit the file and suggest improvements: https://github.com/nschloe/betterbib/blob/master/betterbib/tools.py#L205.

**Comment by keithbriggs** [comment] 2020-06-18 13:03
If I download the new version, it comes with setup.cfg but no setup.py.   So how do I build it?


________________________________

**Comment by nschloe** [comment] 2020-06-18 13:26
I'd just use `pip install betterbib`, see the main readme.

**Comment by keithbriggs** [comment] 2020-06-18 13:27
So pip always gets the latest version?

________________________________

**Comment by nschloe** [comment] 2020-06-18 13:32
The latest from pypi.
